### ISSUE TITLE
[Bug]Not installing kexts

### ISSUE THREAD

**Issue by Blurayx** [chris1111/HWSensors-V6.26.1463-EFI#1]
Hi Chris1111
 It's only installing FakeSMC & HWMonitor
<a href="https://imgur.com/mzlzzrQ"><img src="https://i.imgur.com/mzlzzrQ.png" title="source: imgur.com" /></a>

After install
<a href="https://imgur.com/TZlOUuq"><img src="https://i.imgur.com/TZlOUuq.png" title="source: imgur.com" /></a>

Thanks

**Comment by chris1111** [comment]
Right clic to FakeSMC 
/Show package Contents /Contents/Plugins

**Comment by Blurayx** [comment]
> Right clic to FakeSMC
> /Show package Contents /Contents/Plugins

Ah, Thanks
I still have one problem, I can't see my Radeon RX 5700 XT temps
<a href="https://imgur.com/HGRHXoV"><img src="https://i.imgur.com/HGRHXoV.png" title="source: imgur.com" /></a>

**Comment by chris1111** [comment]
RDNA Architecture are not support

**Comment by Blurayx** [comment]
Do you know an alternative that will work with the  Radeon RX 5700 XT?
Thanks

**Comment by chris1111** [comment]
I don't know?

**Comment by Blurayx** [comment]
OK, Thanks for your help
