### ISSUE TITLE
Zip package release

### ISSUE THREAD

**Issue by 4bitfocus** [chris1111/HWSensors-V6.26.1463-EFI#2]
Would it be possible to release this as a zip file with the raw kext inside? The installer is not working and/or buggy and I don't have any way to manually copy over the kexts from here. A zip file would be ideal.

**Comment by 4bitfocus** [comment]
Disregard the comment about the installer being broken. I was expecting separate kexts for each of the plugins. Instead I see they are installed **inside** of the FakeSMC one. Interesting approach though not immediately obvious. The installer text is really hard to read.

A separate zip package would still be nice.

**Comment by chris1111** [comment]
> Disregard the comment about the installer being broken. I was expecting separate kexts for each of the plugins. Instead I see they are installed **inside** of the FakeSMC one. Interesting approach though not immediately obvious. The installer text is really hard to read.
> 
> A separate zip package would still be nice.


This is the good way but other way is also good.
what is hard to read in the text?
What do you mean by a separate ZIP package? Does it work the way you want it to
